### ISSUE TITLE
Network name instead of code

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/xActivate#3]
![image](https://github.com/XRPL-Labs/xActivate/assets/4756161/679e536c-98aa-489e-8c49-9d93647cff66)

We can use the network rails `name` here instead of the code (key) 

https://xumm.app/api/v1/platform/rails

**Comment by KevinKoobs** [comment]
Fixed in https://github.com/XRPL-Labs/xActivate/commit/d552e334e4ede8bf9152c37925f013200a163226
