### ISSUE TITLE
Mainnet "exchange" "here" buttons

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/xActivate#5]
Looping in you as well @WillXUMM

Also looping in @DJ-xrpl 

I think here the text "An exchange"... and "here" are part of the important flow. Now they are normal text, not bold, just underline, and I think this will result in people missing these (IMPORTANT) options.

Also missing here is our own buy flow, which is actually a revenue stream? The "Buy" xApp; 
https://xumm.app/detect/xapp:xumm.buysellxrp
(xApp Open)

I would expect the first paragraph to stay, and then to have three buttons:

- Learn more about Account Activation
- Buy XRP with fiat (xApp open: buy sell) **Emphasis on this one, this is where we earn something** ⚠️ @KevinKoobs @WillXUMM -- important to figure out how to display this well.
- Exchange deposit instructions

... And then the "use an existing account"

![image](https://github.com/XRPL-Labs/xActivate/assets/4756161/ccb964ab-4dcd-4c82-b5ab-852be1b12c28)

**Comment by WillXUMM** [comment]
"An account on the XRP Ledger is automatically activated when the first 10 XRP is sent to it."

**Comment by WillXUMM** [comment]
![image](https://github.com/XRPL-Labs/xActivate/assets/79937181/c73d80f1-3a2f-4fb8-8541-ba56838a21ad)

**Comment by KevinKoobs** [comment]
@WillXUMM Three buttons with the same color won't work. Therefore, we have three different buttons, but using them here result in a very high bottom part of the page with the instructions falling behind. 

@WietseWind I wasn't aware of the 'Buy' xApp. With four options, we should revamp the design a little bit I think. I'll talk with DJ.

**Comment by DJ-xrpl** [comment]
[Activate Account.pdf](https://github.com/XRPL-Labs/xActivate/files/13474797/Activate.Account.pdf)
@WietseWind @KevinKoobs @WillXUMM how about this

**Comment by KevinKoobs** [comment]
@DJ-xrpl @WillXUMM 

The last screen will not be necessary anymore. Buy via XRPL-Labs is no more, so we only send users to 'BuySell XRP' xApp.

Another thing we've concluded is a change in the buttons: the 'Buy XRP' button is going to be blue to actively push usuers there. We can make money there, so let's get as many users possible over there :)

**Comment by KevinKoobs** [comment]
@DJ-xrpl Clear!

The texts for the bottom two buttons will become 'Fund with existing account' and 'Fund via exchange'. And we ditch 'via Partners' from the top one :)

**Comment by KevinKoobs** [comment]
@DJ-xrpl Not yet, need to build it first :P

**Comment by KevinKoobs** [comment]
Fixed in 025dab098b711e1ed138bca32e7a6f4b8cc473c6
