### ISSUE TITLE
White loader screen

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/xActivate#7]
When opening the xApp, after the Xumm loader, there's a white, blank screen for half a second.

I think (assumption!) that this is before UI render, awaiting XRPL account info about activation.

Two options:

1. Use Xumm Loader and indicate ready post loading everything, when the UI is ready
2. Show the UI with loader, and then kick off the XRPL data fetch and then apply

**Comment by KevinKoobs** [comment]
Fixed in https://github.com/XRPL-Labs/xActivate/commit/f4f56f19bc997edaa60d8a5756276384327d5cf7
